iimport simplegui

# Collatz conjecture states that this sequence 
# always terminates at 1. For example, the sequence 
# generated by 23 is:
# 23, 70, 35, 106, 53, 160, 80, 40, 20, 10, 5, 16, 8, 4, 2, 1

current_number = 0
result = []
collatz_conjecture = 1

def init(start):
    global current_number
    
    current_number = start
    print "Input is", current_number
    
def get_next(current):

    # if even
    if current % 2 == 0:
        current //= 2
    else:
        current = (current * 3) + 1
    return current

def update():
    global result
    global current_number
    
    if current_number == collatz_conjecture:
        timer.stop()
        print "Output is", result
        print "Maximum in array is ", max(result)
    else:
        result.append(current_number)
        current_number = get_next(current_number)

# register event handlers
timer = simplegui.create_timer(1, update)

# start program
init(217)
timer.start()
