#!/usr/bin/env python

import datetime

today = datetime.date.today()
last_year = datetime.date(2007, 8, 1)
print today - last_year

def last_day_of_month(date):
    next_month = date.replace(day=28) + datetime.timedelta(days=4)
    return next_month - datetime.timedelta(days=next_month.day)

for month in range(1, 13):
    print last_day_of_month(datetime.date(2016, month, 1))
